/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.Controller;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Autor;
import model.Knjiga;
import model.Zanr;

/**
 *
 * @author ilija
 */
public class forma extends javax.swing.JDialog {
private Controller kontroler;
private GlavnaForma gf;
private Knjiga knjigaIzmena;
    /**
     * Creates new form forma
     */
    public forma(java.awt.Frame parent, boolean modal, Knjiga knjigaIzmena) {
        super(parent, modal);
        initComponents();
        kontroler = Controller.getInstance();
        this.gf = (GlavnaForma) parent;
        popuniComboBox();
        if(knjigaIzmena !=null){
        this.knjigaIzmena = knjigaIzmena;
        txtNaziv.setText(knjigaIzmena.getNaziv());
        txtISBN.setText(knjigaIzmena.getISBN());
        txtISBN.setEnabled(false);
        cmbZanr.setSelectedItem(knjigaIzmena.getZanr());
        txtGodina.setText(knjigaIzmena.getGodinaIzdavanja()+"");
        btnDodaj.setVisible(false);
        }
        else {
            btnIzmeni.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbAutori = new javax.swing.JComboBox<>();
        txtGodina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbZanr = new javax.swing.JComboBox<>();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        jLabel2.setText("ISBN");

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        jLabel3.setText("Autor");

        cmbAutori.setSelectedIndex(-1);

        txtGodina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGodinaActionPerformed(evt);
            }
        });

        jLabel4.setText("Godina");

        btnDodaj.setText("DODAJ");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        jLabel5.setText("Zanr");

        cmbZanr.setModel(new DefaultComboBoxModel(Zanr.values()));

        btnIzmeni.setText("Izmeni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeni)
                        .addGap(25, 25, 25)
                        .addComponent(btnDodaj)
                        .addGap(27, 27, 27)
                        .addComponent(btnOdustani))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbZanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbAutori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbAutori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnOdustani)
                    .addComponent(btnIzmeni))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtGodinaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.dispose();
    }                                           

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        int godinaIzdanja;
        String naziv;
        String isbn;
        try{
        naziv = txtNaziv.getText();
        isbn = txtISBN.getText();
        godinaIzdanja = Integer.parseInt(txtGodina.getText());}
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Godina izdanja mora biti broj", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
       }
        Zanr zanr = (Zanr) cmbZanr.getSelectedItem();
        Autor autor = (Autor) cmbAutori.getSelectedItem();
        
        Knjiga knjiga = new Knjiga(naziv, autor, isbn, godinaIzdanja, zanr);
        
        
        Controller.getInstance().dodajKnjigu(knjiga);
        gf.osveziTabelu();
        JOptionPane.showMessageDialog(this, "Sve ok", "Lagan si", JOptionPane.INFORMATION_MESSAGE);
    
        this.dispose();
    }                   
    
    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt){
        int godinaIzdanja;
        String naziv;
        String isbn;
        try{
        naziv = txtNaziv.getText();
        isbn = txtISBN.getText();
        godinaIzdanja = Integer.parseInt(txtGodina.getText());}
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Godina izdanja mora biti broj", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
       }
        Zanr zanr = (Zanr) cmbZanr.getSelectedItem();
        Autor autor = (Autor) cmbAutori.getSelectedItem();
        
        knjigaIzmena.setAutor(autor);
        knjigaIzmena.setGodinaIzdavanja(godinaIzdanja);
        knjigaIzmena.setNaziv(naziv);
        knjigaIzmena.setZanr(zanr);
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JComboBox<Autor> cmbAutori;
    private javax.swing.JComboBox<String> cmbZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration                   

    private void popuniComboBox() {
        cmbAutori.removeAllItems();
       List<Autor> autori = kontroler.getListaAutora();
       
       for(Autor a: autori){
           cmbAutori.addItem(a);
       }
    }
}
